# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1dd8b92e7d6a77abf7a91d25fda4832daf6713d26e259c56761f68751de6946a992035babbed5b26deda52b914880a676573f99bfad0065714ee4c3739cad340

test:
  secret_key_base: 54cf26441ec89ab2464ce4934f9c2a2ae48a6a773d8eede541818fcacead48b75965ab015b172d3d0d777024c728b69c973185985c21b54435663a1a53d6c594

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
